{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "iris-operator.fullname" . }}
  labels:
    {{- include "iris-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "iris-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "iris-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
